// TODO: should these strings all be list<u8>?
record request-interface {
  method: string,
  uri: string,
  version: string,
  headers: list<header-interface>,
  chunk: list<u8>,
  chunk-start: u64,
  chunk-length: u64,
  end-of-stream: bool,
}
record header-interface {
  name: string,
  value: string,
}
record decision-interface {
  accept: float64,
  restrict: float64,
  unknown: float64,
}

get-request: func() -> request-interface

set-decision: func(decision: decision-interface)
set-tags: func(tags: list<string>)

get-remote-state: func(key: string) -> list<u8>
set-remote-state: func(key: string, value: list<u8>)
increment-remote-state: func(key: string) -> s64
increment-remote-state-by: func(key: string, delta: s64) -> s64
set-remote-ttl: func(key: string, ttl: s64)
