package bulwark:plugin@0.5.0;

world http-detection {
    include platform;
    export http-handlers;
}

world platform {
    import wasi:cli/environment@0.2.0;
    import wasi:http/outgoing-handler@0.2.0;

    import types;
    import config;
    import redis;
}
