# The purpose of this workflow is to publish the bulwark workspace of crates
# whenever a bulwark release tag is created. This is a simplified version of
# the wasmtime release workflow.

name: "Publish to Crates.io"

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    if: github.repository == 'bulwark-security/bulwark'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203
      with:
        toolchain: stable
        components: clippy
        target: wasm32-wasi

    - name: Ensure generated files are available
      uses: clechasseur/rs-cargo@8435b10f6e71c2e3d4d3b7573003a8ce4bfc6386 # v2.0.2
      with:
        command: test
        args: -p bulwark-config -p bulwark-sdk

    - name: Publish Crates
      run: |
        rustc scripts/publish.rs -o /tmp/publish
        /tmp/publish publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
